---
# This file is maintained by avd_sync.py script.
# Port profiles may be edited manually, but servers will be overwritten on next run.
port_profiles:
  TENANT_A_WAN_SERVICE_10:
    mode: access
    vlans: 10
    spanning_tree_portfast: edge
cpes:
  CPE-1:
    adapters:
    - profile: TENANT_A_WAN_SERVICE_10
      endpoint_ports: [ Ethernet1, Ethernet2 ]
      switch_ports: [ Ethernet5/2, Ethernet52/2 ]
      switches: [ PE-03, PE-04 ]
  CPE-2:
    adapters:
    - profile: TENANT_A_WAN_SERVICE_10
      endpoint_ports: [ Ethernet33, Ethernet34 ]
      switch_ports: [ Ethernet51/3, Ethernet5/3 ]
      switches: [ PE-03, PE-04 ]

