type: rr

# RR Routers
rr:
  defaults:
    platform: jericho
    loopback_ipv4_pool: 100.70.0.0/24
    loopback_ipv6_pool: "2000:1234:ffff:ffff::/64"
    is_type: level-1-2
    node_sid_base: 300
    isis_system_id_prefix: '0000.0000'
    bgp_defaults:
      - 'no bgp default ipv4-unicast'
      - 'distance bgp 20 200 200'
      - 'graceful-restart restart-time 300'
      - 'graceful-restart'
      - 'bgp route-reflector preserve-attributes always'
      # - 'no bgp client-to-client reflection' # If meshing PEs, client-to-client reflection can be turned off
    raw_eos_cli: |
      management security
         password encryption-key common
  node_groups:
    P-01-02:
      bgp_cluster_id: 100.70.0.5
      nodes:
        P-01:
          id: 5
          mgmt_ip: 10.92.61.162/26
        P-02:
          id: 6
          mgmt_ip: 10.92.61.164/26