# IP Reachability tests


- name: validate CPE-01 VPN Services
  hosts: CPE-01

  tasks:

    - name: Gather ip reachability state (directly connected interfaces)
      eos_command:
        commands: "ping {{ item }} repeat 1"
      loop:
        - "vrf VPWS10 10.10.10.2"
        - "vrf tenant-L3EVPN 10.10.200.1"
      ignore_errors: true
      register: ip_reachability_state
      tags:
        - ip_reachability

    - name: Validate ip reachability (directly connected interfaces)
      assert:
        that:
          - ip_reachability_test.stdout[0] | regex_search('1 received')
        fail_msg: "100% packet loss"
        quiet: false
      loop: "{{ ip_reachability_state.results }}"
      loop_control:
        loop_var: ip_reachability_test
      ignore_errors: true
      register: ip_reachability_results
      tags:
        - ip_reachability

- name: validate CPE-02 VPN Services
  hosts: CPE-02

  tasks:

    - name: Gather ip reachability state (directly connected interfaces)
      eos_command:
        commands: "ping {{ item }} repeat 1"
      loop:
        - "vrf VPWS10 10.10.10.1"
        - "vrf tenant-L3EVPN 10.10.100.1"
      ignore_errors: true
      register: ip_reachability_state
      tags:
        - ip_reachability

    - name: Validate ip reachability (directly connected interfaces)
      assert:
        that:
          - ip_reachability_test.stdout[0] | regex_search('1 received')
        fail_msg: "100% packet loss"
        quiet: false
      loop: "{{ ip_reachability_state.results }}"
      loop_control:
        loop_var: ip_reachability_test
      ignore_errors: true
      register: ip_reachability_results
      tags:
        - ip_reachability